"""Shared application boundary for CLI and internal-web adapters."""

from market_research.research.research_project import (
    ResearchProject as ResearchProject,
    ResearchProjectAuthorizationError as ResearchProjectAuthorizationError,
    ResearchProjectConflictError as ResearchProjectConflictError,
    ResearchProjectError as ResearchProjectError,
    ResearchProjectIntegrityError as ResearchProjectIntegrityError,
    ResearchProjectNotFoundError as ResearchProjectNotFoundError,
    ResearchProjectObjectKind as ResearchProjectObjectKind,
    ResearchProjectPermission as ResearchProjectPermission,
    has_research_project_permission as has_research_project_permission,
    project_permission_for_reference as project_permission_for_reference,
)

from .capabilities import (
    CAPABILITIES,
    CapabilityExecutionMode,
    CapabilityRisk,
    CapabilitySpec,
    GuiPolicy,
    capability_registry,
    get_capability,
)
from .authorization import ensure_capability_authorized
from .contracts import (
    ActorContext,
    ApplicationError,
    ApplicationRequest,
    ApplicationResult,
    ApplicationWarning,
    ArtifactReference,
    GovernanceSubjectRef,
    HumanReviewRequest,
    HumanReviewResult,
    IndependentVerificationReference,
    PreflightRequest,
    PreflightResult,
    ReportComparisonRequest,
    ReportComparisonResult,
    ReportComparisonSource,
    ResearchProjectCreateRequest,
    ResearchProjectImpactQueryRequest,
    ResearchProjectMemberInput,
    ResearchProjectMembersRequest,
    ResearchProjectMutationResult,
    ResearchProjectObjectRefInput,
    ResearchProjectQueryRequest,
    ResearchProjectQueryResult,
    ResearchProjectReferenceRequest,
    ResearchProjectRevisionRequest,
    ResearchProjectSearchRequest,
    ResearchProjectSearchResult,
    ResearchProjectTransitionRequest,
    ResearchProjectWorkspaceRequest,
    ResearchProjectWorkspaceResult,
    ResearchPreflightRequest,
    ResearchPreflightResult,
    ResearchReadinessResult,
    ResearchValidationRequest,
    ResearchValidationResult,
    ResearchWorkloadResult,
    ResultStatus,
    RequestedChange,
    StrategyApprovalRequest,
    StrategyApprovalResult,
    ValidationRequest,
    ValidationResult,
)
from .errors import (
    ApplicationAuthorizationError,
    ApplicationCancellation,
    CancellationRequested,
)
from .service import ResearchApplicationService
from .governance_service import ResearchGovernanceApplicationService
from .project_service import ResearchProjectApplicationService
from .release import ReleaseMetadata, ReleaseMetadataError
from .cli_execution import (
    ADMITTED_CLI_EXECUTION_SCOPE,
    LEGACY_WEB_CLAIM_SCOPE,
    LEGACY_WEB_WORKER_SCOPE,
    RESEARCH_JOB_DISPATCH_SCOPE,
    OperatedAdmissionBinding,
    OperatedExecutionDenied,
    ResearchCliOutcome,
    execute_admitted_research_cli,
    is_operated_runtime,
    require_operated_execution_capability,
)

__all__ = [
    "ActorContext",
    "ADMITTED_CLI_EXECUTION_SCOPE",
    "ApplicationAuthorizationError",
    "ApplicationCancellation",
    "ApplicationError",
    "ApplicationRequest",
    "ApplicationResult",
    "ApplicationWarning",
    "ArtifactReference",
    "CAPABILITIES",
    "CancellationRequested",
    "CapabilityExecutionMode",
    "CapabilityRisk",
    "CapabilitySpec",
    "GuiPolicy",
    "GovernanceSubjectRef",
    "HumanReviewRequest",
    "HumanReviewResult",
    "IndependentVerificationReference",
    "LEGACY_WEB_CLAIM_SCOPE",
    "LEGACY_WEB_WORKER_SCOPE",
    "OperatedAdmissionBinding",
    "OperatedExecutionDenied",
    "PreflightRequest",
    "PreflightResult",
    "ReportComparisonRequest",
    "ReportComparisonResult",
    "ReportComparisonSource",
    "ResearchPreflightRequest",
    "ResearchPreflightResult",
    "ResearchProjectApplicationService",
    "ResearchProject",
    "ResearchProjectAuthorizationError",
    "ResearchProjectConflictError",
    "ResearchProjectCreateRequest",
    "ResearchProjectError",
    "ResearchProjectImpactQueryRequest",
    "ResearchProjectIntegrityError",
    "ResearchProjectMemberInput",
    "ResearchProjectMembersRequest",
    "ResearchProjectMutationResult",
    "ResearchProjectNotFoundError",
    "ResearchProjectObjectKind",
    "ResearchProjectObjectRefInput",
    "ResearchProjectPermission",
    "ResearchProjectQueryRequest",
    "ResearchProjectQueryResult",
    "ResearchProjectReferenceRequest",
    "ResearchProjectRevisionRequest",
    "ResearchProjectSearchRequest",
    "ResearchProjectSearchResult",
    "ResearchProjectTransitionRequest",
    "ResearchProjectWorkspaceRequest",
    "ResearchProjectWorkspaceResult",
    "ResearchReadinessResult",
    "ResearchApplicationService",
    "ResearchGovernanceApplicationService",
    "RESEARCH_JOB_DISPATCH_SCOPE",
    "ReleaseMetadata",
    "ReleaseMetadataError",
    "ResearchCliOutcome",
    "ResearchValidationRequest",
    "ResearchValidationResult",
    "ResearchWorkloadResult",
    "ResultStatus",
    "RequestedChange",
    "StrategyApprovalRequest",
    "StrategyApprovalResult",
    "ValidationRequest",
    "ValidationResult",
    "capability_registry",
    "get_capability",
    "has_research_project_permission",
    "ensure_capability_authorized",
    "execute_admitted_research_cli",
    "is_operated_runtime",
    "project_permission_for_reference",
    "require_operated_execution_capability",
]
