"""Shared application boundary for CLI and internal-web adapters."""

from .capabilities import (
    CAPABILITIES,
    CapabilityExecutionMode,
    CapabilityRisk,
    CapabilitySpec,
    GuiPolicy,
    capability_registry,
    get_capability,
)
from .authorization import ensure_capability_authorized
from .contracts import (
    ActorContext,
    ApplicationError,
    ApplicationRequest,
    ApplicationResult,
    ApplicationWarning,
    ArtifactReference,
    GovernanceSubjectRef,
    HumanReviewRequest,
    HumanReviewResult,
    PreflightRequest,
    PreflightResult,
    ReportComparisonRequest,
    ReportComparisonResult,
    ReportComparisonSource,
    ResearchPreflightRequest,
    ResearchPreflightResult,
    ResearchReadinessResult,
    ResearchValidationRequest,
    ResearchValidationResult,
    ResearchWorkloadResult,
    ResultStatus,
    RequestedChange,
    StrategyApprovalRequest,
    StrategyApprovalResult,
    ValidationRequest,
    ValidationResult,
)
from .errors import (
    ApplicationAuthorizationError,
    ApplicationCancellation,
    CancellationRequested,
)
from .service import ResearchApplicationService
from .governance_service import ResearchGovernanceApplicationService

__all__ = [
    "ActorContext",
    "ApplicationAuthorizationError",
    "ApplicationCancellation",
    "ApplicationError",
    "ApplicationRequest",
    "ApplicationResult",
    "ApplicationWarning",
    "ArtifactReference",
    "CAPABILITIES",
    "CancellationRequested",
    "CapabilityExecutionMode",
    "CapabilityRisk",
    "CapabilitySpec",
    "GuiPolicy",
    "GovernanceSubjectRef",
    "HumanReviewRequest",
    "HumanReviewResult",
    "PreflightRequest",
    "PreflightResult",
    "ReportComparisonRequest",
    "ReportComparisonResult",
    "ReportComparisonSource",
    "ResearchPreflightRequest",
    "ResearchPreflightResult",
    "ResearchReadinessResult",
    "ResearchApplicationService",
    "ResearchGovernanceApplicationService",
    "ResearchValidationRequest",
    "ResearchValidationResult",
    "ResearchWorkloadResult",
    "ResultStatus",
    "RequestedChange",
    "StrategyApprovalRequest",
    "StrategyApprovalResult",
    "ValidationRequest",
    "ValidationResult",
    "capability_registry",
    "get_capability",
    "ensure_capability_authorized",
]
