# Generated by Django 5.2.16 on 2026-07-17 08:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("portal", "0008_imported_decision_report"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceAccessGrant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("MANIFEST", "Manifest"),
                            ("EXPERIMENT", "Experiment"),
                            ("STRATEGY", "Strategy"),
                        ],
                        max_length=16,
                    ),
                ),
                ("resource_id", models.CharField(max_length=255)),
                (
                    "access",
                    models.CharField(
                        choices=[
                            ("VIEW", "View"),
                            ("SUBMIT", "Submit research"),
                            ("REVIEW", "Review"),
                        ],
                        max_length=16,
                    ),
                ),
                ("rationale", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "granted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="research_resource_access_grants_issued",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "principal_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="research_resource_access_grants",
                        to="auth.group",
                    ),
                ),
                (
                    "principal_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="research_resource_access_grants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("resource_type", "resource_id", "access", "created_at"),
                "indexes": [
                    models.Index(
                        fields=["resource_type", "resource_id", "access"],
                        name="portal_resource_grant_lookup",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("principal_group__isnull", True),
                                ("principal_user__isnull", False),
                            ),
                            models.Q(
                                ("principal_group__isnull", False),
                                ("principal_user__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="portal_resource_grant_one_principal",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("resource_id", ""), _negated=True),
                            models.Q(("rationale", ""), _negated=True),
                        ),
                        name="portal_resource_grant_fields_required",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("principal_user__isnull", False)),
                        fields=(
                            "principal_user",
                            "resource_type",
                            "resource_id",
                            "access",
                        ),
                        name="portal_resource_user_grant_uniq",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("principal_group__isnull", False)),
                        fields=(
                            "principal_group",
                            "resource_type",
                            "resource_id",
                            "access",
                        ),
                        name="portal_resource_group_grant_uniq",
                    ),
                ],
            },
        ),
    ]
