"""First-class offline futures and options research contracts.

The package contains no broker, account, live-order, or network data code.
Every market input is an externally prepared immutable snapshot and every
execution object is a research-only simulated object.
"""

from .common import (
    AvailabilityTimes,
    DatasetCompleteness,
    DerivativeDatasetFilterContract,
    DerivativeDatasetSnapshot,
    DerivativeExperimentRun,
    DerivativeExperimentSpec,
    DerivativeResearchError,
    FuturesDatasetFilterContract,
    InstrumentKind,
    OptionDatasetFilterContract,
    QualityDecision,
    QualityResult,
    RunType,
    derivative_dataset_filter_from_dict,
)
from .portfolio import (
    PORTFOLIO_EXPOSURE_AGGREGATION_POLICY,
    PORTFOLIO_EXPOSURE_AGGREGATION_POLICY_HASH,
    ExpiryConcentration,
    ExposureAggregate,
    ExposureGroup,
    PortfolioExposureSnapshot,
    PositionEvidenceHashes,
    PositionExposure,
    StressPnL,
    StressPnLAggregate,
    stress_set_hash,
)
from .monitoring import (
    EXPECTED_DRIFT_METHOD,
    METRIC_DIMENSIONS,
    PROSPECTIVE_MONITORING_SCHEMA_VERSION,
    DriftMethod,
    FrozenMonitoringSpec,
    MetricDriftRule,
    MetricMonitoringDecision,
    MetricObservation,
    MonitoringArtifactRef,
    MonitoringMetric,
    MonitoringOutcome,
    MonitoringProductKind,
    ObservationRole,
    ProspectiveMonitoringArtifact,
    evaluate_prospective_monitoring,
    required_metrics,
)
from .evidence import (
    knowledge_archive_evidence_ref,
    monitoring_artifact_evidence_ref,
    risk_artifact_evidence_ref,
)
from .knowledge_evidence import (
    DERIVATIVE_KNOWLEDGE_EVIDENCE_SCHEMA_VERSION,
    DERIVATIVE_RESEARCH_CONCLUSION_AUTHORITY,
    DerivativeKnowledgeEvidenceArchive,
    DerivativeKnowledgeEvidenceError,
    verify_derivative_knowledge_evidence_archive,
)
from .risk_metrics import (
    DerivativeRiskEvidence,
    DerivativeRiskMetric,
    RiskMetricId,
    RiskMetricStatus,
    RiskMetricValue,
    RiskProductKind,
    build_futures_risk_evidence,
    build_option_risk_evidence,
)
from .simulation_evidence import (
    SIMULATION_EVIDENCE_SCHEMA_VERSION,
    DerivativeSimulationEvidence,
    OptionExecutionMode,
    OptionExecutionPolicy,
    OptionOrderIntentEvidence,
    SimulationEvidenceError,
    SimulationProductKind,
    futures_fill_model_hash,
)
from .workflow import (
    DERIVATIVE_EVIDENCE_BUNDLE_SCHEMA_VERSION,
    DerivativeEvidenceBundle,
    DerivativeEvidenceWorkflowError,
    diff_derivative_evidence_packages,
    register_derivative_evidence_bundle,
    replay_derivative_evidence_bundle,
)

__all__ = [
    "AvailabilityTimes",
    "DatasetCompleteness",
    "DerivativeDatasetFilterContract",
    "DerivativeDatasetSnapshot",
    "DerivativeExperimentRun",
    "DerivativeExperimentSpec",
    "DerivativeResearchError",
    "FuturesDatasetFilterContract",
    "InstrumentKind",
    "OptionDatasetFilterContract",
    "QualityDecision",
    "QualityResult",
    "RunType",
    "derivative_dataset_filter_from_dict",
    "PORTFOLIO_EXPOSURE_AGGREGATION_POLICY",
    "PORTFOLIO_EXPOSURE_AGGREGATION_POLICY_HASH",
    "ExpiryConcentration",
    "ExposureAggregate",
    "ExposureGroup",
    "PortfolioExposureSnapshot",
    "PositionEvidenceHashes",
    "PositionExposure",
    "StressPnL",
    "StressPnLAggregate",
    "stress_set_hash",
    "EXPECTED_DRIFT_METHOD",
    "METRIC_DIMENSIONS",
    "PROSPECTIVE_MONITORING_SCHEMA_VERSION",
    "DriftMethod",
    "FrozenMonitoringSpec",
    "MetricDriftRule",
    "MetricMonitoringDecision",
    "MetricObservation",
    "MonitoringArtifactRef",
    "MonitoringMetric",
    "MonitoringOutcome",
    "MonitoringProductKind",
    "ObservationRole",
    "ProspectiveMonitoringArtifact",
    "evaluate_prospective_monitoring",
    "required_metrics",
    "monitoring_artifact_evidence_ref",
    "risk_artifact_evidence_ref",
    "knowledge_archive_evidence_ref",
    "DERIVATIVE_KNOWLEDGE_EVIDENCE_SCHEMA_VERSION",
    "DERIVATIVE_RESEARCH_CONCLUSION_AUTHORITY",
    "DerivativeKnowledgeEvidenceArchive",
    "DerivativeKnowledgeEvidenceError",
    "verify_derivative_knowledge_evidence_archive",
    "DerivativeRiskEvidence",
    "DerivativeRiskMetric",
    "RiskMetricId",
    "RiskMetricStatus",
    "RiskMetricValue",
    "RiskProductKind",
    "build_futures_risk_evidence",
    "build_option_risk_evidence",
    "SIMULATION_EVIDENCE_SCHEMA_VERSION",
    "DerivativeSimulationEvidence",
    "OptionExecutionMode",
    "OptionExecutionPolicy",
    "OptionOrderIntentEvidence",
    "SimulationEvidenceError",
    "SimulationProductKind",
    "futures_fill_model_hash",
    "DERIVATIVE_EVIDENCE_BUNDLE_SCHEMA_VERSION",
    "DerivativeEvidenceBundle",
    "DerivativeEvidenceWorkflowError",
    "diff_derivative_evidence_packages",
    "register_derivative_evidence_bundle",
    "replay_derivative_evidence_bundle",
]
